drop   index if exists Book_Name;
create  unique index Book_Name on Book ( Name) ;
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Genesis','Old',1);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Exodus','Old',2);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Leviticus','Old',3);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Numbers','Old',4);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Deuteronomy','Old',5);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Joshua','Old',6);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Judges','Old',7);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Ruth','Old',8);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Samuel','Old',9);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Samuel','Old',10);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Kings','Old',11);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Kings','Old',12);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Chronicles','Old',13);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Chronicles','Old',14);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Ezra','Old',15);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Nehemiah','Old',16);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Esther','Old',17);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Job','Old',18);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Psalm','Old',19);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Proverbs','Old',20);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Ecclesiastes','Old',21);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Song of Solomon','Old',22);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Isaiah','Old',23);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Jeremiah','Old',24);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Lamentations','Old',25);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Ezekiel','Old',26);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Daniel','Old',27);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Hosea','Old',28);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Joel','Old',29);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Amos','Old',30);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Obadiah','Old',31);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Jonah','Old',32);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Micah','Old',33);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Nahum','Old',34);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Habakkuk','Old',35);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Zephaniah','Old',36);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Haggai','Old',37);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Zechariah','Old',38);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Malachi','Old',39);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Matthew','New',40);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Mark','New',41);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Luke','New',42);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'John','New',43);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Acts','New',44);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Romans','New',45);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Corinthians','New',46);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Corinthians','New',47);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Galatians','New',48);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Ephesians','New',49);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Philippians','New',50);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Colossians','New',51);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Thessalonians','New',52);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Thessalonians','New',53);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Timothy','New',54);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Timothy','New',55);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Titus','New',56);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Philemon','New',57);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Hebrews','New',58);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'James','New',59);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 Peter','New',60);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 Peter','New',61);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'1 John','New',62);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'2 John','New',63);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'3 John','New',64);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Jude','New',65);
insert or ignore INTO Book (Id,Name,Testament,Ordinal) VALUES (lower(hex(randomblob(16))),'Revelation','New',66);